tripadvisor: tripadvisor.py
	rm -rf ../../data/tripadvisor.json
	scrapy runspider ./tripadvisor.py -o ../../data/tripadvisor.json

lonely: lonely.py
	rm -rf ../../data/lonely.json
	scrapy runspider ./lonely.py -o ../../data/lonely.json

myswitzerland: myswitzerland.py
	rm -rf ../../data/myswitzerland.json
	scrapy runspider ./myswitzerland.py -o ../../data/myswitzerland.json
