tripadvisor: tripadvisor.py
	rm -rf ../../data/tripadvisor.json
	scrapy runspider ./tripadvisor.py -o ../../data/tripadvisor.json

booking: booking.py
	rm -rf ../../data/booking.json
	scrapy runspider ./booking.py -o ../../data/booking.json
